In [1]:
import pandas as pd
import numpy as np

In [1]:
#Create a 0 dimension, 1 dimension and 2 dimension numpy array
# 0 dimension array
arr0=123
print(arr0)
# 1 dimension array
arr1=[1,2,3]
print(arr1)
# 2 dimension array
arr2=[[1,2,3],[4,5,6]]
print(arr2)

123
[1, 2, 3]
[[1, 2, 3], [4, 5, 6]]


In [10]:
#- Create a 2 dimension array and

arr=[[1,2,3],[4,5,6]]
print(arr1)

print("Sum of array elements:", np.sum(arr))
print("Minimum value in array:", np.min(arr))
print("Maximum value in array:", np.max(arr))
print("Mean of array elements:", np.mean(arr))
print("Median of array elements:", np.median(arr))
print("Standard deviation of array elements:", np.std(arr))


[1, 2, 3]
Sum of array elements: 21
Minimum value in array: 1
Maximum value in array: 6
Mean of array elements: 3.5
Median of array elements: 3.5
Standard deviation of array elements: 1.707825127659933


In [11]:
#Create a 1 dimension array using np.arange()
arr3d = np.arange(1,13)
print("1D array:\n",arr3d)

#Then restructure that same array using np.reshape() to 2 dimension array.
arr4d = arr3d.reshape(6, 2)
print("reshape:",arr4d)

# Transpose that array to opposite of the same reshaped array.
arr5d = arr4d.transpose()
print("transpose:",arr5d)

#Flatten the same array to normal array that we created first.
arr6d=arr5d.flatten()
print("flatten:",arr5d)

1D array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
reshape: [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
transpose: [[ 1  3  5  7  9 11]
 [ 2  4  6  8 10 12]]
flatten: [[ 1  3  5  7  9 11]
 [ 2  4  6  8 10 12]]


In [12]:
#Create a 2 dimension array using nested list
arr7d=np.array([[10,11,12],[4,5,6],[7,8,9]])
print(arr7d)

# use np.sort() to sort the array
arr10=np.sort(arr7d)
print("sorted array\n:",arr10)

#use np.sort()[::-1] to reverse the sorted array.
sorting=np.sort(arr7d)[::-1]
print("reverse\n :",sorting)

#use np.size() to check the size and np.shape() to check the shape of the array
sized=np.size(arr7d)
print("size:\n",sized)

[[10 11 12]
 [ 4  5  6]
 [ 7  8  9]]
sorted array
: [[10 11 12]
 [ 4  5  6]
 [ 7  8  9]]
reverse
 : [[ 7  8  9]
 [ 4  5  6]
 [10 11 12]]
size:
 9


In [13]:
arr2d = np.array([[1,2,3,4],
                  [4,5,6,7],
                  [7,8,9,10]])
# Use this array and access 1st last two elements from the array (9,10)
print(arr2d[2, 2:3])
# Use this array and access only last column elements (4,7,10)
print(arr2d[-1, -2:])

[9]
[ 9 10]


In [16]:
import pandas as pd
#Create a Series of 1 to 1000 with pd.series() hint >> list[range(1,1001)]

data=list(range(1,1001))
series = pd.Series(data)

print(series)
#Create a DataFrame of 5 students with subjects as maths, physics, chemistry
data = {
    "Maths": [85, 78, 92, 88, 76],
    "Physics": [80, 74, 89, 90, 70],
    "Chemistry": [75, 82, 91, 85, 73]
}
df = pd.DataFrame(data)
print(df)
#Access df.shape, df.size, df.info, df.describe() of the following students data
print(df.shape)
print(df.size)
print(df.info)
print(df.describe())

0         1
1         2
2         3
3         4
4         5
       ... 
995     996
996     997
997     998
998     999
999    1000
Length: 1000, dtype: int64
   Maths  Physics  Chemistry
0     85       80         75
1     78       74         82
2     92       89         91
3     88       90         85
4     76       70         73
(5, 3)
15
<bound method DataFrame.info of    Maths  Physics  Chemistry
0     85       80         75
1     78       74         82
2     92       89         91
3     88       90         85
4     76       70         73>
           Maths    Physics  Chemistry
count   5.000000   5.000000   5.000000
mean   83.800000  80.600000  81.200000
std     6.723095   8.876936   7.362065
min    76.000000  70.000000  73.000000
25%    78.000000  74.000000  75.000000
50%    85.000000  80.000000  82.000000
75%    88.000000  89.000000  85.000000
max    92.000000  90.000000  91.000000


In [18]:
data=pd.read_csv(r"C:\Users\SHRUTI\Downloads\bengaluru_house_prices.csv")
data
print(data.columns)      # show column names
print(data)
print(data[['area', 'bedrooms', 'bathrooms', 'location', 'price']])
top10 = data.sort_values(by="price", ascending=False).head(10)
print(top10)
bottom10 = data.sort_values(by="price").head(10)
print(bottom10)
print(data.isnull().sum())
print(data.duplicated().sum())  
df = data.drop_duplicates()    
data["price"] = df["price"].fillna(df["price"].mean())
data = data.dropna()
print(data["price"])
print(data[["area", "price"]])
print(data[data["price"] > 100])
print(data.loc[0])                      
print(data.loc[0:3, ["area", "price"]]) 
print(data.loc[df["price"] > 100])     
print(data.iloc[0])          
print(data.iloc[0:3, 0:2])   







Index(['area_type', 'availability', 'location', 'size', 'society',
       'total_sqft', 'bath', 'balcony', 'price'],
      dtype='object')
                  area_type   availability                  location  \
0      Super built-up  Area         19-Dec  Electronic City Phase II   
1                Plot  Area  Ready To Move          Chikka Tirupathi   
2            Built-up  Area  Ready To Move               Uttarahalli   
3      Super built-up  Area  Ready To Move        Lingadheeranahalli   
4      Super built-up  Area  Ready To Move                  Kothanur   
...                     ...            ...                       ...   
13315        Built-up  Area  Ready To Move                Whitefield   
13316  Super built-up  Area  Ready To Move             Richards Town   
13317        Built-up  Area  Ready To Move     Raja Rajeshwari Nagar   
13318  Super built-up  Area         18-Jun           Padmanabhanagar   
13319  Super built-up  Area  Ready To Move              Doddathoguru 

KeyError: "['area', 'bedrooms', 'bathrooms'] not in index"